// generated by cdk8s
import { ApiObject, ApiObjectMetadata, GroupVersionKind } from 'cdk8s';
import { Construct } from 'constructs';


/**
 *
 *
 * @schema Metric
 */
export class Metric extends ApiObject {
  /**
   * Returns the apiVersion and kind for "Metric"
   */
  public static readonly GVK: GroupVersionKind = {
    apiVersion: 'autoscaling.internal.knative.dev/v1alpha1',
    kind: 'Metric',
  }

  /**
   * Renders a Kubernetes manifest for "Metric".
   *
   * This can be used to inline resource manifests inside other objects (e.g. as templates).
   *
   * @param props initialization props
   */
  public static manifest(props: MetricProps = {}): any {
    return {
      ...Metric.GVK,
      ...toJson_MetricProps(props),
    };
  }

  /**
   * Defines a "Metric" API object
   * @param scope the scope in which to define this object
   * @param id a scope-local name for the object
   * @param props initialization props
   */
  public constructor(scope: Construct, id: string, props: MetricProps = {}) {
    super(scope, id, {
      ...Metric.GVK,
      ...props,
    });
  }

  /**
   * Renders the object to Kubernetes JSON.
   */
  public toJson(): any {
    const resolved = super.toJson();

    return {
      ...Metric.GVK,
      ...toJson_MetricProps(resolved),
    };
  }
}

/**
 * @schema Metric
 */
export interface MetricProps {
  /**
   * @schema Metric#metadata
   */
  readonly metadata?: ApiObjectMetadata;

}

/**
 * Converts an object of type 'MetricProps' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_MetricProps(obj: MetricProps | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'metadata': obj.metadata,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */


/**
 *
 *
 * @schema PodAutoscaler
 */
export class PodAutoscaler extends ApiObject {
  /**
   * Returns the apiVersion and kind for "PodAutoscaler"
   */
  public static readonly GVK: GroupVersionKind = {
    apiVersion: 'autoscaling.internal.knative.dev/v1alpha1',
    kind: 'PodAutoscaler',
  }

  /**
   * Renders a Kubernetes manifest for "PodAutoscaler".
   *
   * This can be used to inline resource manifests inside other objects (e.g. as templates).
   *
   * @param props initialization props
   */
  public static manifest(props: PodAutoscalerProps = {}): any {
    return {
      ...PodAutoscaler.GVK,
      ...toJson_PodAutoscalerProps(props),
    };
  }

  /**
   * Defines a "PodAutoscaler" API object
   * @param scope the scope in which to define this object
   * @param id a scope-local name for the object
   * @param props initialization props
   */
  public constructor(scope: Construct, id: string, props: PodAutoscalerProps = {}) {
    super(scope, id, {
      ...PodAutoscaler.GVK,
      ...props,
    });
  }

  /**
   * Renders the object to Kubernetes JSON.
   */
  public toJson(): any {
    const resolved = super.toJson();

    return {
      ...PodAutoscaler.GVK,
      ...toJson_PodAutoscalerProps(resolved),
    };
  }
}

/**
 * @schema PodAutoscaler
 */
export interface PodAutoscalerProps {
  /**
   * @schema PodAutoscaler#metadata
   */
  readonly metadata?: ApiObjectMetadata;

}

/**
 * Converts an object of type 'PodAutoscalerProps' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_PodAutoscalerProps(obj: PodAutoscalerProps | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'metadata': obj.metadata,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

